In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [8]:
import numpy as np   
a =np.array([1,2,3])# one dimensional

In [9]:
type(a)

numpy.ndarray

In [10]:
a.shape # to check rows and columns

(3,)

In [11]:
a[0]

1

In [13]:
b = np.array([[1,2,3],[4,6,7]])# 2 dimensional - count number of square brackets at beginning

In [14]:
type(a)

numpy.ndarray

In [16]:
b.shape

(2, 3)

In [17]:
b[0]

array([1, 2, 3])

In [18]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1])

In [19]:
#generate random numbers
np.random.rand(2,3)

array([[0.68708113, 0.01628718, 0.13249469],
       [0.96722398, 0.64458751, 0.19128156]])

In [20]:
np.random.randn(4,5)  #Return a sample from the "standard normal distrubution from -1 to +1

array([[-0.95459216, -2.23963073,  0.35984859, -0.02184759,  1.17189872],
       [ 0.29357794,  1.84839288, -1.76195877, -0.29879871, -1.1454412 ],
       [-0.95706185, -0.67311347,  1.42179636,  0.17919854,  1.30544799],
       [ 0.83416826, -0.71073739, -1.57467539, -1.32274731,  0.51707768]])

In [22]:
np.round(np.random.randn(4,5),3)# round off to 3 digits

array([[ 0.141, -0.095,  0.164, -1.029,  2.34 ],
       [ 1.459,  0.113,  0.36 ,  0.292, -0.268],
       [-0.836,  0.109, -0.921, -0.552, -0.06 ],
       [ 1.575, -0.061,  0.388, -0.263,  0.27 ]])

In [23]:
np.random.randint(10,100,(6,5)) #randint(low, high=None, size=None, dtype=int)

                                 #Return random integers from `low` (inclusive) to `h

array([[36, 55, 80, 51, 52],
       [80, 53, 87, 58, 90],
       [67, 93, 27, 81, 13],
       [94, 94, 80, 69, 61],
       [20, 62, 24, 72, 25],
       [63, 36, 47, 42, 37]])

In [24]:
np.full((2,2),7)# an array filled with any values and pass in shape of the desired array

array([[7, 7],
       [7, 7]])

In [25]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
# to get an evenly spaces array of numbers using np.arrange()
np.arange(5)

array([0, 1, 2, 3, 4])

In [28]:
#arange(start, stop, interval, dtype=None, *, like=None)
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [29]:
np.linspace(4,20,4)

array([ 4.        ,  9.33333333, 14.66666667, 20.        ])

In [33]:
#to check the dimension
b.ndim

2

In [34]:
b.shape

(2, 3)

In [36]:
b.size # nimber of values in array

6

In [37]:
#reshape the array
np.reshape(b,(3,2))

array([[1, 2],
       [3, 4],
       [6, 7]])

In [38]:
np.reshape(b,(6,1))

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7]])

In [42]:
#to acess value
b[1][1]

6

In [45]:
#to change value
b[1][1]=3

In [46]:
b

array([[1, 2, 3],
       [4, 3, 7]])

In [47]:
d = np.array([1,2,3,4,5,6])
print(d[1:5:2])

[2 4]


In [4]:
c = np.random.randon(2,3)# horizontal stacking
f = np.random.randon(2,4)# vertical stacking
np.hstack((c,f))

NameError: name 'np' is not defined